### PR TITLE
Update Author details

### PR DESCRIPTION
**Pull request by tphysics**
Yolo Co's!

### CODE REVIEW

**Comment by PrieureDeSion** [comment]
G+ profile is incorrect..

Correct it to ` +toshi.tanu08 ` or whatever..!
Good going on a PR! :smile:

**Comment by PrieureDeSion** [comment]
@tphysics Make your image changes and author changes in one commit and PR.

**Comment by PrieureDeSion** [comment]
Arey hagga hai @tphysics 
Should have built before merging. Check this out
http://mnp-club.github.io/blog/blackhole-paradox/

**Comment by tphysics** [comment]
Don't get you



Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=toshi.tanu08@gmail.com&idSignature=22>


Toshi Parmar


*Convener, Maths & Physics ClubJunior Design Engineer, IITB Racing*Sophomore
Undergraduate
Engineering Physics
IIT Bombay

**Comment by PrieureDeSion** [comment]
Check out the link.
http://mnp-club.github.io/blog/blackhole-paradox/

The author field  is supposed to look somewhat like this:
http://mnp-club.github.io/blog/universe

**Comment by tphysics** [comment]
Okay
So?
That was done AGES ago by me
The context remains out of reach of my memory


Toshi Parmar


*Convener, Maths & Physics ClubJunior Design Engineer, IITB Racing*Sophomore
Undergraduate
Engineering Physics
IIT Bombay

**Comment by PrieureDeSion** [comment]
Unfortunate.

**Comment by PrieureDeSion** [comment]
Your issue has been sorted. Check your blog and let me know if any other issue has missed me.

You're welcome.

**Pull request merged**
